Repository Skatteetaten/vagrant-hashistack-template, pull requests merged in 2020-09, with the labels that each got.

#3 Update 01_build_docker_image.yml
  template_example/dev/ansible/01_build_docker_image.yml
Labels: enhancement

#6 Fix links in doc
  CHANGELOG.md
  README.md
Labels: documentation

#15 feature/template-example-test
  .github/linters/.tflint.hcl
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
Labels: theme/ci, theme/test, type/enchancement

#30 Add consul namespace documentation
  CHANGELOG.md
  README.md
Labels: type/documentation
