Repository Skatteetaten/vagrant-hashistack-template, pull requests merged in 2020-11, with the labels that each got.

#70 Updated and fixed READMEs ++
  .github/_README.md
  CHANGELOG.md
  GETTING_STARTED/README.md
  GETTING_STARTED/getting_started_modules.md
  GETTING_STARTED/getting_started_vagrantbox.md
  README.md
  README_template.md
  conf/README.md
  conf/nomad/README.md
  dev/README.md
  dev/ansible/README.md
  dev/vagrant/README.md
  dev/vagrant/bootstrap/README.md
  dev/vagrant/conf/README.md
  dev/vagrant/conf/consul/README.md
  dev/vagrant/conf/nomad/README.md
  dev/vagrant/conf/vault/README.md
  docker/README.md
  docker/conf/certificates/README.md
  example/README.md
  example/vagrant_box_example/README.md
  template_example/dev/vagrant/bootstrap/README.md
  template_example/docker/conf/certificates/README.md
Labels: type/documentation

#75 Updated box version :rocket:
  CHANGELOG.md
  Vagrantfile.default
  template_example/example/standalone/providers.tf
Labels: type/enchancement

#77 changed set-env
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  template_example/example/standalone/providers.tf
Labels: type/enchancement

#78 Fixed box ansible args
  CHANGELOG.md
  Vagrantfile.default
Labels: type/bug

#85 Dynamic use of consul_token
  template_example/dev/ansible/00_create_intention.yml
  template_example/dev/ansible/03_healthcheck_test.yml
  template_example/example/standalone/providers.tf
  template_example/example/standalone/variables.tf
Labels: skip-changelog, type/enchancement

#86 Tutorials
  CHANGELOG.md
  GETTING_STARTED/README.md
  GETTING_STARTED/tutorials.md
  README.md
Labels: type/documentation
