Repository Skatteetaten/vagrant-hashistack-template, pull requests merged in 2020-10, with the labels that each got.

#36 Add terraform-provider-vault token
  CHANGELOG.md
  template_example/example/standalone/main.tf
  template_example/example/standalone/providers.tf
Labels: type/enchancement

#39 Updated makefile targets up and template_example
  CHANGELOG.md
  Makefile
Labels: theme/ci

#40 Add doc: sync module with the latest template AND pre-commit fix
  CHANGELOG.md
  Makefile
  README.md
Labels: type/documentation

#43 Automate release process
  .github/action/find-replace.py
  .github/workflows/on_pr_push_master.yml
Labels: type/enchancement

#46 Updated makefile targets up and template_example
  .github/action/find-replace.py
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  Makefile
Labels: type/enchancement

#51 Bumped vagrant version. Removed extra lines in Makefile
  CHANGELOG.md
  Makefile
  Vagrantfile.default
Labels: type/enchancement

#49 Added getting started section
  CHANGELOG.md
  README.md
  getting_started_modules.md
  getting_started_vagrantbox.md
Labels: type/documentation

#61 Fixed formatting content header
  getting_started_modules.md
Labels: skip-changelog

#62 Added github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: theme/ci

#63 Healthcheck countdash
  CHANGELOG.md
  template_example/dev/ansible/00_create_intention.yml
  template_example/dev/ansible/03_healthcheck_test.yml
Labels: theme/test

#73 expanded auto_correct doc
  README.md
Labels: skip-changelog
